"""Report generation — HTML and Jupyter Notebook outputs."""

from __future__ import annotations

import base64
import datetime
import json
from pathlib import Path
from typing import Any

from jinja2 import Environment, FileSystemLoader, select_autoescape

from .agent import CodeStep, Finding

TEMPLATES_DIR = Path(__file__).parent / "templates"


def _b64_image(path: str) -> str:
    """Return a data-URI string for an image file, or empty string on failure."""
    try:
        data = Path(path).read_bytes()
        encoded = base64.b64encode(data).decode()
        return f"data:image/png;base64,{encoded}"
    except Exception:
        return ""


def generate_html_report(
    profile: dict[str, Any],
    findings: list[Finding],
    summary: str,
) -> str:
    """Render the HTML report with inline base64 charts."""

    env = Environment(
        loader=FileSystemLoader(str(TEMPLATES_DIR)),
        autoescape=select_autoescape(["html"]),
    )
    env.filters["b64image"] = _b64_image
    template = env.get_template("report.html")

    # Sort findings: high → medium → low
    priority = {"high": 0, "medium": 1, "low": 2}
    sorted_findings = sorted(findings, key=lambda f: priority.get(f.importance, 1))

    return template.render(
        profile=profile,
        findings=sorted_findings,
        summary=summary,
        generated_at=datetime.datetime.now().strftime("%Y-%m-%d %H:%M"),
    )


# ---------------------------------------------------------------------------
# Jupyter Notebook
# ---------------------------------------------------------------------------

def _make_nb_cell(cell_type: str, source: str | list[str], **kwargs: Any) -> dict[str, Any]:
    """Build a single notebook cell dict."""
    if isinstance(source, str):
        source = source.splitlines(keepends=True)
        # Ensure last line ends with newline
        if source and not source[-1].endswith("\n"):
            source[-1] += "\n"
    cell: dict[str, Any] = {
        "cell_type": cell_type,
        "metadata": {},
        "source": source,
    }
    if cell_type == "code":
        cell["execution_count"] = kwargs.get("execution_count")
        cell["outputs"] = kwargs.get("outputs", [])
    return cell


def _text_output(text: str) -> dict[str, Any]:
    """Create a notebook stream-output block."""
    return {
        "output_type": "stream",
        "name": "stdout",
        "text": text.splitlines(keepends=True),
    }


def _image_output(path: str) -> dict[str, Any] | None:
    """Create a notebook display_data output with an embedded PNG."""
    b64 = _b64_image_raw(path)
    if not b64:
        return None
    return {
        "output_type": "display_data",
        "metadata": {},
        "data": {
            "image/png": b64,
        },
    }


def _b64_image_raw(path: str) -> str:
    """Return raw base64 string (no data-URI prefix) for a PNG file."""
    try:
        data = Path(path).read_bytes()
        return base64.b64encode(data).decode()
    except Exception:
        return ""


def generate_notebook(
    profile: dict[str, Any],
    findings: list[Finding],
    code_steps: list[CodeStep],
    summary: str,
) -> str:
    """Generate a Jupyter Notebook (.ipynb) that reproduces the analysis.

    The notebook contains:
      1. Title + executive summary (markdown)
      2. Setup / imports cell
      3. Data-loading cell (user fills in their path)
      4. Data-profile overview (markdown)
      5. Each executed code step with its purpose as a heading
      6. Findings as markdown narrative cells
      7. Closing summary
    """

    cells: list[dict[str, Any]] = []
    exec_counter = 1

    # ── 1. Title ──────────────────────────────────────────────────────────
    cells.append(_make_nb_cell("markdown", (
        "# Exploratory Data Analysis Report\n"
        "\n"
        f"*Generated by EDA Agent on {datetime.datetime.now().strftime('%Y-%m-%d %H:%M')}*\n"
        "\n"
        "This notebook contains all the code the AI agent executed during its\n"
        "autonomous analysis. You can re-run each cell to reproduce the results.\n"
    )))

    # ── 2. Executive Summary ──────────────────────────────────────────────
    cells.append(_make_nb_cell("markdown", (
        "## Executive Summary\n"
        "\n"
        f"{summary}\n"
    )))

    # ── 3. Setup cell ─────────────────────────────────────────────────────
    setup_code = (
        "# Setup — run this cell first\n"
        "import pandas as pd\n"
        "import numpy as np\n"
        "import matplotlib\n"
        "matplotlib.use('Agg')  # or remove this line for inline display\n"
        "import matplotlib.pyplot as plt\n"
        "import seaborn as sns\n"
        "import warnings\n"
        "warnings.filterwarnings('ignore')\n"
        "\n"
        "%matplotlib inline\n"
        "plt.rcParams['figure.figsize'] = (10, 6)\n"
        "sns.set_theme(style='whitegrid')\n"
    )
    cells.append(_make_nb_cell("code", setup_code, execution_count=exec_counter))
    exec_counter += 1

    # ── 4. Data loading cell ──────────────────────────────────────────────
    cells.append(_make_nb_cell("markdown", (
        "## Load Data\n"
        "\n"
        "Replace the path below with the location of your dataset.\n"
    )))

    load_code = (
        "# Update the path to your dataset file\n"
        "DATA_PATH = 'your_dataset.csv'  # <-- CHANGE THIS\n"
        "\n"
        "df = pd.read_csv(DATA_PATH)\n"
        "print(f'Loaded {len(df):,} rows x {len(df.columns)} columns')\n"
        "df.head()\n"
    )
    cells.append(_make_nb_cell("code", load_code, execution_count=exec_counter))
    exec_counter += 1

    # ── 5. Data profile (markdown) ────────────────────────────────────────
    s = profile["shape"]
    q = profile["quality"]
    profile_lines = (
        "## Data Profile\n"
        "\n"
        f"| Metric | Value |\n"
        f"|--------|-------|\n"
        f"| Rows | {s['rows']:,} |\n"
        f"| Columns | {s['columns']} |\n"
        f"| Memory | {profile['memory_usage_mb']} MB |\n"
        f"| Missing values | {q['total_missing_pct']}% |\n"
        f"| Duplicate rows | {q['duplicate_rows']} |\n"
        "\n"
        "| Column | Type | Role | Missing % | Unique |\n"
        "|--------|------|------|-----------|--------|\n"
    )
    for col in profile["columns"]:
        profile_lines += (
            f"| {col['name']} | {col['dtype']} | {col['role']} "
            f"| {col['missing_pct']}% | {col['unique']} |\n"
        )
    cells.append(_make_nb_cell("markdown", profile_lines))

    # ── 6. Analysis code steps ────────────────────────────────────────────
    cells.append(_make_nb_cell("markdown", "## Analysis\n\nThe following cells reproduce every step the AI agent performed.\n"))

    for i, step in enumerate(code_steps, 1):
        # Heading for this step
        cells.append(_make_nb_cell("markdown", f"### Step {i}: {step.purpose}\n"))

        # Build outputs
        outputs: list[dict[str, Any]] = []
        if step.stdout.strip():
            outputs.append(_text_output(step.stdout))
        if step.error:
            outputs.append({
                "output_type": "stream",
                "name": "stderr",
                "text": step.error.splitlines(keepends=True),
            })
        for fig_path in step.figures:
            img = _image_output(fig_path)
            if img:
                outputs.append(img)

        cells.append(_make_nb_cell(
            "code",
            step.code,
            execution_count=exec_counter,
            outputs=outputs,
        ))
        exec_counter += 1

    # ── 7. Findings (markdown) ────────────────────────────────────────────
    if findings:
        cells.append(_make_nb_cell("markdown", "## Key Findings\n"))

        priority = {"high": 0, "medium": 1, "low": 2}
        sorted_findings = sorted(findings, key=lambda f: priority.get(f.importance, 1))

        for i, finding in enumerate(sorted_findings, 1):
            cells.append(_make_nb_cell("markdown", (
                f"### {i}. {finding.title}\n"
                "\n"
                f"{finding.narrative}\n"
            )))

    # ── 8. Closing ────────────────────────────────────────────────────────
    cells.append(_make_nb_cell("markdown", (
        "---\n"
        "\n"
        "*Notebook generated by [EDA Agent](https://github.com) — autonomous AI-powered data analysis.*\n"
    )))

    # ── Assemble notebook ─────────────────────────────────────────────────
    notebook = {
        "nbformat": 4,
        "nbformat_minor": 5,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
            "language_info": {
                "name": "python",
                "version": "3.11.0",
                "mimetype": "text/x-python",
                "file_extension": ".py",
            },
        },
        "cells": cells,
    }

    return json.dumps(notebook, indent=1, ensure_ascii=False)


