"""Report generation — HTML and Markdown outputs."""

from __future__ import annotations

import base64
import datetime
from pathlib import Path
from typing import Any

from jinja2 import Environment, FileSystemLoader, select_autoescape

from .agent import Finding

TEMPLATES_DIR = Path(__file__).parent / "templates"


def _b64_image(path: str) -> str:
    """Return a data-URI string for an image file, or empty string on failure."""
    try:
        data = Path(path).read_bytes()
        encoded = base64.b64encode(data).decode()
        return f"data:image/png;base64,{encoded}"
    except Exception:
        return ""


def generate_html_report(
    profile: dict[str, Any],
    findings: list[Finding],
    summary: str,
) -> str:
    """Render the HTML report with inline base64 charts."""

    env = Environment(
        loader=FileSystemLoader(str(TEMPLATES_DIR)),
        autoescape=select_autoescape(["html"]),
    )
    env.filters["b64image"] = _b64_image
    template = env.get_template("report.html")

    # Sort findings: high → medium → low
    priority = {"high": 0, "medium": 1, "low": 2}
    sorted_findings = sorted(findings, key=lambda f: priority.get(f.importance, 1))

    return template.render(
        profile=profile,
        findings=sorted_findings,
        summary=summary,
        generated_at=datetime.datetime.now().strftime("%Y-%m-%d %H:%M"),
    )


def generate_markdown_report(
    profile: dict[str, Any],
    findings: list[Finding],
    summary: str,
) -> str:
    """Generate a Markdown report."""

    lines: list[str] = []
    lines.append("# Exploratory Data Analysis Report")
    lines.append("")
    lines.append(f"*Generated on {datetime.datetime.now().strftime('%Y-%m-%d %H:%M')}*")
    lines.append("")

    # Executive summary
    lines.append("## Executive Summary")
    lines.append("")
    lines.append(summary)
    lines.append("")

    # Data overview
    lines.append("## Data Overview")
    lines.append("")
    s = profile["shape"]
    q = profile["quality"]
    lines.append(f"- **Rows:** {s['rows']:,}")
    lines.append(f"- **Columns:** {s['columns']}")
    lines.append(f"- **Memory:** {profile['memory_usage_mb']} MB")
    lines.append(f"- **Missing values:** {q['total_missing_pct']}%")
    lines.append(f"- **Duplicate rows:** {q['duplicate_rows']}")
    lines.append("")

    lines.append("### Column Details")
    lines.append("")
    lines.append("| Column | Type | Role | Missing % | Unique |")
    lines.append("|--------|------|------|-----------|--------|")
    for col in profile["columns"]:
        lines.append(
            f"| {col['name']} | {col['dtype']} | {col['role']} "
            f"| {col['missing_pct']}% | {col['unique']} |"
        )
    lines.append("")

    # Findings
    priority = {"high": 0, "medium": 1, "low": 2}
    sorted_findings = sorted(findings, key=lambda f: priority.get(f.importance, 1))

    lines.append("## Key Findings")
    lines.append("")

    for i, finding in enumerate(sorted_findings, 1):
        badge = {"high": "HIGH", "medium": "MEDIUM", "low": "LOW"}.get(
            finding.importance, "MEDIUM"
        )
        lines.append(f"### {i}. {finding.title}  `[{badge}]`")
        lines.append("")
        lines.append(finding.narrative)
        lines.append("")
        for chart_path in finding.chart_paths:
            rel_path = Path(chart_path).name
            lines.append(f"![{finding.title}](figures/{rel_path})")
            lines.append("")

    lines.append("---")
    lines.append("*Report generated by [EDA Agent](https://github.com) — autonomous AI-powered data analysis.*")

    return "\n".join(lines)


def generate_pdf_report(html_content: str, output_path: str | Path) -> bool:
    """Convert HTML report to PDF. Returns True on success."""
    try:
        from xhtml2pdf import pisa

        with open(output_path, "wb") as f:
            status = pisa.CreatePDF(html_content, dest=f)
        return not status.err
    except Exception:
        return False
